swagger: "2.0"
info:
  description: "This is documentation for pendulum instances built using Node & Express."
  version: "1.0.0"
  title: "Simple Pendulum"
  contact:
    email: "work@humzakhan.net"
basePath: "/v1"
tags:
- name: "config"
  description: "Endpoints to manage a pendulum's configuration"
- name: "position"
  description: "Endpoints to manage a pendulum's position"
schemes:
- "http"
paths:
  /config:
    put:
      tags:
      - "config"
      summary: "Add new config to the pendulum"
      description: ""
      operationId: "configurePendulum"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Configuration object for the pendulum"
        required: true
        schema:
          $ref: "#/definitions/config"
      responses:
        "400":
          description: "Invalid input"
        "201":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/config"
    get:
      tags:
      - "config"
      summary: "Get config for a pendulum"
      description: ""
      operationId: "getPendulumConfig"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "config found and returned"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/position"
              
  /position:
    put:
      tags:
      - "position"
      summary: "Record pendulum's latest position"
      description: ""
      operationId: "updatePosition"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Latest position of the pendulum"
        required: true
        schema:
          $ref: "#/definitions/position"
      responses:
        "400":
          description: "Invalid input"
        "201":
          description: "Position saved successfully"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/position"
    get:
      tags:
      - "position"
      summary: "Get latest position for a pendulum"
      description: ""
      operationId: "getCurrentPosition"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "position found and returned"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/position"

definitions:
  config:
    type: "object"
    properties:
      initialOffset:
        type: "integer"
        format: "float"
      mass:
        type: "integer"
        format: "int32"
      stringLength: 
        type: "integer"
        format: "int32"
      maximumWindFactor:
        type: "integer"
        format: "int32"
      color:
        type: "string"
        format: "string"
        
  position:
    type: "object"
    properties:
      x:
        type: "integer"
        format: "int32"
      y:
        type: "integer"
        format: "int32"
  
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"